version: "3"
services:
  receiver:
    build:
      context: ./Receiver
    image: receiver-image
    container_name: receiver-container
    ports:
      - 8080:8080
    networks:
      appnetwork:
        ipv4_address: 172.30.0.2

  storage:
    build:
      context: ./storage
    image: storage-image
    container_name: storage-container
    ports:
      - 8090:8090

    networks:
      appnetwork:
        ipv4_address: 172.30.0.3

  processing:
    build:
      context: ./processing
    image: processing-image
    container_name: processing-container
    ports:
      - 8100:8100
    networks:
      appnetwork:
        ipv4_address: 172.30.0.4

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      appnetwork:
        ipv4_address: 172.30.0.5

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://lOCALHOST:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      appnetwork:
        ipv4_address: 172.30.0.6

  mysql:
    build:
      context: ./mysql
    image: mysql-image
    container_name: mysql-container
    ports:
      - 3306:3306
    networks:
      appnetwork:
        ipv4_address: 172.30.0.11
    volumes:
      - joy-mysql-file:/var/lib/mysql

networks:
  appnetwork:
    external: true
 
volumes:
  joy-mysql-file:

